---
title: "Pointing Experimental data"
author: "Carmen Saldana"
date: "`r Sys.Date()`"
output:
  html_document: 
    number_sections: true
  pdf_document: default
# bibliography: [path]
header-includes: 
  \usepackage{tipa}
  \usepackage{color}
  \setlength\parindent{12pt}
citation_package: natbib
biblio-style: apa6
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r preamble libraries, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(lme4) 
library(kableExtra)
library(broom.mixed)
library(brms)
```

```{r functions, echo=FALSE, warning=FALSE, message=FALSE}
'%!in%' <- function(x,y)!('%in%'(x,y))

se <- function(x) sqrt(var(x)/length(x))

pd <- position_dodge(0.8)

# function to run model, if .Rds already exists, it just opens it, if it does not it runs the model and saves it as .Rds in the path given
run_model <- function(expr, path, reuse = TRUE) {
  path <- paste0(path, ".Rds")
  if (reuse) {
    fit <- suppressWarnings(try(readRDS(path), silent = TRUE))
  }
  if (is(fit, "try-error")) {
    fit <- eval(expr)
    saveRDS(fit, file = path)
  }
  fit
}
```

# Data Analysis
```{r import data, echo=FALSE, warning=FALSE, message=FALSE}
data.pointing <- read.csv("data.csv", header = TRUE)
```

## Data visualisation
```{r plot data, echo=FALSE, warning=FALSE, message=FALSE}
data.pointing <- data.pointing %>% 
  mutate(type = type %>% 
           fct_recode( declarative = "decl", imperative = "imp") 
         ) %>% 
  mutate(correct_response = ifelse(correct == "correct", 1, 0)) 

data_plots <- data.pointing %>% 
  group_by(condition, type, ID) %>% 
  summarise_each(list(mean=mean, se=se),correct_response) %>% 
  ungroup()

data_plots.central <- data.pointing %>% 
  group_by(condition, type) %>% 
  summarise_each(list(mean=mean, se=se),correct_response) %>% 
  ungroup()


plot.pointing <- ggplot(data=data_plots , aes(x=type, y=mean, fill=type)) + 
  scale_fill_brewer(palette="YlGnBu") + 
  theme_minimal() + 
  geom_violin(trim=FALSE)+
  geom_dotplot(binaxis = "y", stackdir = "center", dotsize=0.5, position=pd, alpha=0.4)+
  # geom_errorbar(data=data_plots.central, mapping=aes(x = type, ymin=mean-se, ymax=mean+se), width=.2, inherit.aes = FALSE)+
  # geom_point(shape=21,size=2, data=data_plots.central, mapping=aes(y=mean, x=type),  stroke=1) +
  stat_summary(fun.data = "mean_cl_boot", colour = "black", size = 1)+
  facet_grid(. ~ condition)+
  labs( x="\n type of point", y = "proportion of correct responses \n")+
  theme(axis.text=element_text(size=11), axis.title=element_text(size=13),legend.position="none", plot.title=element_text(size=11),strip.text.x = element_text(size = 12))
            
plot.pointing
```

```{r freq model, echo=FALSE, warning=FALSE, message=FALSE, eval = FALSE}
mod.freq <- glmer(correct_response ~ condition*type + (1+type|ID)  + (1|stim_number), data = data.pointing, family="binomial", control = glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=17700)), contrasts=list(type="contr.sum", condition = "contr.sum"))

kable(tidy(mod.freq, effects = "fixed"), digits= 3, format = "html", caption = "Model: correct ~ condition*type + (1+type|ID)  + (1|stim_number). Categorical variables are sum coded.")%>% kable_styling( "striped", position = "left", font_size = 11)

```

## Bayesian model

### Priors
```{r binomial  bayesian prior, warning=FALSE, message=FALSE}

Prior <- c(
    set_prior("student_t(6, 0, 1.5)", class = "Intercept"),
    set_prior("student_t(6, 0, 1.5)", class = "b"),
    set_prior("cauchy(0, 10)", class = "sd")
)
```

### Model
```{r Bayesian model,  warning=FALSE, message=FALSE}
path.model.bayes.pointing <- paste0(getwd(),"/mod.bayes.binomial.pointing")

options(contrasts=c("contr.sum","contr.poly"))

mod.pointing.bayes.binomial <- run_model(
      brm(formula = correct_response | trials(1) ~ condition*type + (1+type|ID)  + (1|stim_number),
           data= data.pointing,
           family = binomial,
           prior = Prior,
           sample_prior = TRUE,
           warmup = 1000,
           iter = 4000,
           chains = 4,
           inits= "0",
           cores=4,
           seed = 123, 
           save_pars = save_pars(all = TRUE)),
      path.model.bayes.pointing)
```

### Results
```{r summary model bayes pointing, echo=FALSE, warning=FALSE, message=FALSE}
kable(tidy(mod.pointing.bayes.binomial, conf.level = 0.90, effects = "fixed"), digits= 3, format = "html", caption = "Mean estimates and 90%CIs. Binomial model: *correct ~ condition*type + (1+type|ID)  + (1|stim_number)*. Sum contrast coding.")%>% kable_styling( "striped", position = "left", font_size = 11)


ht.pointing <- hypothesis(mod.pointing.bayes.binomial, c("Intercept > 0","condition1 > 0",'type1>0', 'condition1:type1>0'))

kable(data.frame(ht.pointing$hypothesis$Hypothesis,ht.pointing$hypothesis$Post.Prob), digits= 3, format = "html", caption = "Fixed effects' posterior probabilities above 0.")%>%
  kable_styling( "striped", position = "left", font_size = 11)
```

#### Data with overlay model means
```{r plot darta with model results, echo=FALSE, warning=FALSE, message=FALSE}
marg.eff.pointing <- brms::marginal_effects(mod.pointing.bayes.binomial, new_objects = list(trials = 1), probs = c(0.05,0.95))


plot.pointing.mod <- ggplot(data=data_plots , aes(x=type, y=mean, fill=type)) + 
  scale_fill_brewer(palette="YlGnBu") + 
  theme_minimal() + 
  geom_violin(trim=FALSE)+
  geom_dotplot(binaxis = "y", stackdir = "center", dotsize=0.5, position=pd, alpha=0.4)+
  geom_pointrange(data=marg.eff.pointing[[3]], mapping=aes(x = type, y = estimate__,ymin=lower__, ymax=upper__),inherit.aes = FALSE, size =1)+
  facet_grid(. ~ condition)+
  labs( x="\n type of point", y = "proportion of correct responses \n")+
  theme(axis.text=element_text(size=11), axis.title=element_text(size=13),legend.position="none", plot.title=element_text(size=11),strip.text.x = element_text(size = 12))

plot.pointing.mod       
```

